### PR TITLE
Let user choose formatter

### PR DESCRIPTION
**Pull request by bronzdoc**
Hi, i noticed i can't override the pre-set formatter. 

When you pass the `--format` flag to rspec it just appends the formatter you want to use to what you have as default. It doesn't overwrite it, so no matter what format i choose it always showing the `documentation` format. It will be nice if people be available to choose which formatter to use.

### CODE REVIEW

**Comment by zuazo** [comment]
@bronzdoc thanks for the PR! :wink:

Do you know if there is a way to change the default values without disabling the possibility of changing them later?

**Comment by bronzdoc** [comment]
Hey @zuazo :slightly_smiling_face: 

Yes,  you create a `.rspec` file with the content `--format documentation` for example,  so you don't have to pass the `--format` flag everytime you run the specs. You can create this file at home directory level or at project level. (In dockerspec this only works if configuration file don't exists)

I don't know if that responds your question :sweat_smile:

**Comment by zuazo** [comment]
@bronzdoc, thanks for quick answer.

What I would like to know is if there is a way to do it inside the dockerspec library, to avoid simply eliminating that code. I mean, if we can change default RSpec configuration values inside *lib/dockerspec/rspec/configuration.rb* .

If you do not know, I'll look to see if I can find a way.

**Comment by bronzdoc** [comment]
Oh, yeah i don't know about that

**Comment by zuazo** [comment]
Fixed in 3483b597f47c23c6e58b15053f6c7cb9d83dec34.

Thanks for your help!

**Comment by bronzdoc** [comment]
Thanks @zuazo

**Comment by zuazo** [comment]
Released in [`0.4.0`](https://github.com/zuazo/dockerspec/releases/tag/0.4.0).

**Pull request closed without merging**
